#pragma kernel EnvironmentDisplayUpdate

bool bDisplayHeightmapEdgeDetectionLayer;


RWTexture2D<float4> LandFieldLayerMap;
RWTexture2D<float4> HeightMapEdgeDetectionLayerMap;

RWTexture2D<float4> EnvironmentDisplayAllMap;

int width;
int height;

[numthreads(8, 8, 1)]
void EnvironmentDisplayUpdate (uint3 id : SV_DispatchThreadID)
{
    if (id.x < 0 || id.x >= (uint) width || id.y < 0 || id.y >= (uint) height)
    {
        return;
    }
    
    
    float4 heightmapedge = HeightMapEdgeDetectionLayerMap[id.xy];
    float4 colour = 0;
    
    if(bDisplayHeightmapEdgeDetectionLayer)
    {
        if (heightmapedge.x > 0
        && heightmapedge.y > 0
        && heightmapedge.z > 0
        && heightmapedge.w > 0)
        {
            colour = heightmapedge;

        }
        else
        {
            colour = LandFieldLayerMap[id.xy];
        }
    }
    else
    {
        colour = LandFieldLayerMap[id.xy];
    }
    
    EnvironmentDisplayAllMap[id.xy] = colour;
}

